

clean-run: clean-install run-dist

clean-install:
	./gradlew clean installDist


install:
	./gradlew clean install


build:
	./gradlew clean build



test:
	./gradlew test

report:
	./gradlew jacocoTestReport


.PHONY: build
